server:
  port: 9000
spring:
  profiles:
    active: local-dev
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
---
spring:
  profiles:
    active: local-mariadb-dev
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: flex
    password: flex
    driver-class-name: org.mariadb.jdbc.Driver
#logging.level:
#  org.hibernate.SQL: debug
